CREATE TABLE contacts (
  id_contact NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  email VARCHAR(40) NOT NULL,
  phone NUMBER(20),
  city VARCHAR(30) NOT NULL,
  street VARCHAR(30) NOT NULL,
  CONSTRAINT pk_contacts PRIMARY KEY (id_contact)
);

CREATE TABLE students (
  id_student NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  pesel VARCHAR(11) NOT NULL,
  id_contact NUMBER NOT NULL,
  date_birth DATE NOT NULL,
  CONSTRAINT pk_students PRIMARY KEY (id_student),
  CONSTRAINT fk_contacts_students FOREIGN KEY (id_contact) REFERENCES contacts(id_contact)
);

CREATE TABLE teachers (
  id_teacher NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  first_name VARCHAR(30)NOT NULL,
  last_name VARCHAR(30)NOT NULL,
  id_contact NUMBER NOT NULL,
  date_birth DATE NOT NULL,
  CONSTRAINT pk_teachers PRIMARY KEY (id_teacher),
  CONSTRAINT fk_contact_teachers FOREIGN KEY (id_contact) REFERENCES contacts(id_contact) 
);

CREATE TABLE subjects (
  id_subject NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  name_subject VARCHAR(30) NOT NULL,
  id_student NUMBER NOT NULL,
  id_teacher NUMBER NOT NULL,
  mark INT NOT NULL,
  CONSTRAINT check_mark CHECK (mark BETWEEN 2 AND 5),
  CONSTRAINT pk_subject PRIMARY KEY (id_subject),
  CONSTRAINT fk_students_subjects FOREIGN KEY (id_student) REFERENCES students(id_student),
  CONSTRAINT fk_teachers_subjects FOREIGN KEY (id_teacher) REFERENCES teachers(id_teacher)
);

CREATE TABLE payments (
  id_payment NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)NOT NULL,
  id_student NUMBER NOT NULL,
  installment INT NOT NULL,
  state_pay NUMBER(1) DEFAULT 0,
  CONSTRAINT pk_payments PRIMARY KEY(id_payment),
  CONSTRAINT fk_payments_students FOREIGN KEY (id_payment) REFERENCES students(id_student)
);

CREATE TABLE group_of_students(
  name_group VARCHAR(30) NOT NULL,
  id_student NUMBER NOT NULL,
  CONSTRAINT fk_group_of_students FOREIGN KEY (id_student) REFERENCES students(id_student)
);