CREATE OR REPLACE FUNCTION example_function(v_id_customer IN INT, v_count_product IN INT, v_name_product IN VARCHAR)
RETURN BOOLEAN
IS
v_price NUMBER (4,2);
v_id_product INT;
v_finally_price NUMBER(6,2);

BEGIN
SELECT price, id_product
INTO v_price, v_id_product
FROM table_test_product
WHERE product_name = v_name_product;

v_finally_price := v_price * v_count_product;

INSERT INTO table_test2_orders (id_customer, id_product, count_product, finally_price) VALUES (v_id_customer, v_id_product, v_count_product, v_finally_price);

END;


CREATE OR REPLACE TRIGGER example_trigger
AFTER INSERT ON table_test2_orders
FOR EACH ROW
WHEN (new.finally_price > 2000)
DECLARE
v_promotion NUMBER(4,1);
v_end_date DATE;
BEGIN
IF new.finally_price < 3000 THEN
  v_promotion := new.finally_price * 0.1;
ELSIF new.finally_price BETWEEN 3000 AND 5000 THEN
  v_promotion := new.finally_price * 0.13;
ELSE
  v_promotion := new.finally_price * 0.15;
END IF;
v_end_date := ADD_MONTHS(CURRENT_DATE, 2);
  INSERT INTO table_test3_promotions (id_customer, promotion, start_date, end_date) VALUES (new.id_customer, v_promotion, CURRENT_DATE, v_end_date );
END;


CREATE TABLE table_test_product (
  id_product INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  product_name VARCHAR2(60) NOT NULL,
  price NUMBER(5,2) NOT NULL,
  CONSTRAINT pk_table_test PRIMARY KEY (id_product)
  );
  
CREATE TABLE table_test2_orders (
id_order INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
id_customer INTEGER,
id_product INTEGER,
count_product INTEGER,
finally_price NUMBER(6, 2),
CONSTRAINT pk_able_test_2 PRIMARY KEY (id_order))

