CREATE OR REPLACE PROCEDURE generate_invoices (v_id_user IN INT)
IS
v_x INT := 1;
v_year VARCHAR(4) := TO_CHAR(CURRENT_DATE, 'YYYY');
v_date DATE;
BEGIN


WHILE v_x <= 12 LOOP
SELECT TO_DATE('05/' || v_x ||'/'||v_year , 'DD/MM/YYYY')
INTO v_date
FROM dual;
INSERT INTO final_invoices(id_user, end_date, state) VALUES(v_id_user, TO_DATE(v_date, 'DD/MM/YYYY'), 1);
v_x := v_x + 1;
END LOOP;
END;

CALL generate_invoices (1);

SELECT *
FROM final_invoices;


CREATE TABLE final_invoices (
  id_final_invoices INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  id_user INT NOT NULL,
  end_date DATE,
  state CHAR(1),
  CONSTRAINT pk_final_invoices PRIMARY KEY (id_final_invoices)
  );
  
drop table final_invoices;