CREATE TABLE aa_product(
id_product INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
name_product VARCHAR2(20),
id_promotion INTEGER,
price NUMBER(8,2),
CONSTRAINT pk_aa_product PRIMARY KEY (id_product),
CONSTRAINT fk_product_promotion FOREIGN KEY (id_promotion) REFERENCES aa_promotion(id_promotion)
);

CREATE TABLE aa_promotion(
id_promotion INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
name_promotion VARCHAR2(100),
percent_of_promotion INTEGER,
CONSTRAINT pk_aa_promotion PRIMARY KEY(id_promotion),
CONSTRAINT chceck_percent_of_promotion CHECK(percent_of_promotion IN (10, 20, 30, 40, 50))
);

CREATE TABLE aa_product_in_promotion (
id_product_in_promotion INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
id_product INTEGER,
new_price NUMBER(8, 2),
CONSTRAINT pk_product_in_promotion PRIMARY KEY (id_product_in_promotion),
CONSTRAINT fk_product_in_promotion_product FOREIGN KEY (id_product) REFERENCES aa_product(id_product)
);

INSERT INTO aa_promotion(name_promotion, percent_of_promotion) VALUES('Promocja 10%', 10);
INSERT INTO aa_promotion(name_promotion, percent_of_promotion) VALUES('Promocja 20%', 20);
INSERT INTO aa_promotion(name_promotion, percent_of_promotion) VALUES('Promocja 30%', 30);
INSERT INTO aa_promotion(name_promotion, percent_of_promotion) VALUES('Promocja 40%', 40);
INSERT INTO aa_promotion(name_promotion, percent_of_promotion) VALUES('Promocja 50%', 50);

CREATE OR REPLACE TRIGGER create_promotion
AFTER INSERT OR UPDATE
ON aa_product
FOR EACH ROW

DECLARE
number_promotion NUMBER(2,1);
result_price NUMBER(8,2);

BEGIN
IF(:new.id_promotion IS NOT NULL)
THEN
    IF :new.id_promotion = 1
    THEN number_promotion := 0.1;
    ELSIF :new.id_promotion = 2
    THEN number_promotion := 0.2;
    ELSIF :new.id_promotion = 3
    THEN number_promotion := 0.3;
    ELSIF :new.id_promotion = 4
    THEN number_promotion := 0.4;
    
    ELSE number_promotion := 0.5;
    END IF;
    result_price := :new.price - (:new.price * number_promotion);
    DBMS_OUTPUT.PUT_LINE(result_price);
    INSERT INTO aa_product_in_promotion(id_product, new_price) VALUES(:new.id_product, result_price);
ELSE
NULL;
END IF;

END;

COMMIT;

